### ISSUE TITLE
cp1250 decoder error

### ISSUE THREAD

**Issue by madmaxoft** [ammaraskar/pyCraft#36] opened 2015-04-17 12:31 UTC
I have tried running `start.py` under Python 3.4 (64-bit) on Windows 7. I'm getting this on the console:
```
Logged in as <redacted>
Exception in thread Networking Thread:
Traceback (most recent call last):
  File "C:\Python34\lib\threading.py", line 921, in _bootstrap_inner
    self.run()
  File "<path>\pyCraft\minecraft\networking\connection.py", line 179, in run
    self.connection.file_object)
  File "<path>\pyCraft\minecraft\networking\connection.py", line 215, in read_packet
    packet_data.send(stream.read(length))
  File "C:\Python34\lib\encodings\cp1250.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 21: character maps to <undefined>
```

What can I do to help track this down?

My module versions:
- cryptography 0.8.2
- pyasn1 0.1.7
- pycparser 2.10
- requests 2.6
- six 1.9
Running via Python Tools for Visual Studio 2010

**Comment by ammaraskar** [comment] 2015-04-17 12:44
Duplicate of #29

**Closed by ammaraskar** 2015-04-17 12:44 UTC
Labels: py3 compatibility
