### ISSUE TITLE
No module named 'minecraft.authentication'

### ISSUE THREAD

**Issue by ViperLands** [ammaraskar/pyCraft#207] opened 2020-12-18 22:57 UTC
i did `pip install git+https://github.com/ammaraskar/pyCraft/` 

and when trying to import authentification lib i got

`No module named 'minecraft.authentication`

any one help pls

**Comment by joodicator** [comment] 2020-12-19 07:36
Duplicate of #63

**Closed by joodicator** 2020-12-19 07:36 UTC
Labels: duplicate, invalid
