### ISSUE TITLE
Does this work on 1.10?

### ISSUE THREAD

**Issue by vanjavk** [ammaraskar/pyCraft#50] opened 2016-10-01 12:18 UTC
I have spigot 1.10 running and when I try to connect it just says logged in and nothing happens: http://i.imgur.com/CYf4D1U.png

**Comment by Bottersnike** [comment] 2016-10-01 13:18
#49 might be of use

**Comment by joodicator** [comment] 2016-10-01 14:57
Thank you for the report. This was a bug in pyCraft caused by missing protocol version data for 1.10.1 and 1.10.2, and an infinite loop in the automatic protocol version negotiator.

It should be fixed now in 7ab7381261245868b51ba7d22bdafea06f477d9a.

**Closed** 2016-10-01 14:58 UTC
Labels: bug

**Comment by vanjavk** [comment] 2016-10-01 15:10
Hello, I first tried downloading protocolsupport as mention in #49 however it didn't help, then I downloaded your new version and it didn't work, only after I deleted protocolsupport it started working.
So for anyone else in future, protocolsupport might prevent you from connecting.

**Comment by joodicator** [comment] 2016-10-01 15:50
For compatibility with the ProtocolSupport plugin for Spigot, it may be necessary to specify the initial protocol version as one (presumably the highest) that ProtocolSupport supports using the `initial_version` argument of the `minecraft.networking.connection.Connection` constructor. Otherwise, pyCraft attempts to connect using its highest supported version (snapshot 16w39c as of this post) and receives a disconnect message from ProtocolSupport that it does not understand.

The `start.py` example that comes with pyCraft doesn't support setting the protocol version as a command-line argument, but it could be easily modified to do so. My own [mcchat2](//github.com/joodicator/mcchat2) is an example of a more complicated client using pyCraft that supports this functionality.

Alternatively, pyCraft could be modified to support ProtocolSupport automatically, but since this is not a vanilla issue, I'm not sure it belongs on the main branch.
