### ISSUE TITLE
start.py crashes after a short while if -d is passed

### ISSUE THREAD

**Issue by Fisk24** [ammaraskar/pyCraft#133] opened 2019-07-03 11:49 UTC
Im new to minecraft's packet protocol so i was trying to see that the demo client was receiving and go from there. However it seems to crash when attempting to process the UpdateLatencyPacket

Here is the relevant traceback:

Exception in thread Networking Thread:

Traceback (most recent call last):
  File "/home/fisk/Projects/MCBOT/pyCraft/minecraft/networking/connection.py", line 544, in run
    self._run()
  File "/home/fisk/Projects/MCBOT/pyCraft/minecraft/networking/connection.py", line 582, in _run
    self.connection._react(packet)
  File "/home/fisk/Projects/MCBOT/pyCraft/minecraft/networking/connection.py", line 518, in _react
    listener.call_packet(packet)
  File "/home/fisk/Projects/MCBOT/pyCraft/minecraft/networking/packets/packet_listener.py", line 15, in call_packet
    self.callback(packet)
  File "start.py", line 87, in print_incoming
    print('--> %s' % packet, file=sys.stderr)
  File "/home/fisk/Projects/MCBOT/pyCraft/minecraft/networking/packets/packet.py", line 116, in __repr__
    for a in fields if hasattr(self, a))
  File "/home/fisk/Projects/MCBOT/pyCraft/minecraft/networking/packets/packet.py", line 116, in <genexpr>
    for a in fields if hasattr(self, a))
  File "/home/fisk/Projects/MCBOT/pyCraft/minecraft/networking/packets/clientbound/play/player_list_item_packet.py", line 28, in field_string
    return super(PlayerListItemPacket, self).field_string(field)
  File "/home/fisk/Projects/MCBOT/pyCraft/minecraft/networking/packets/packet.py", line 139, in field_string
    return repr(value)
  File "/home/fisk/Projects/MCBOT/pyCraft/minecraft/networking/types/utility.py", line 68, in __repr__
    '%s=%r' % (a, getattr(self, a)) for a in self._all_slots()))
  File "/home/fisk/Projects/MCBOT/pyCraft/minecraft/networking/types/utility.py", line 68, in <genexpr>
    '%s=%r' % (a, getattr(self, a)) for a in self._all_slots()))
AttributeError: 'UpdateLatencyAction' object has no attribute 'p'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/fisk/Projects/MCBOT/pyCraft/minecraft/networking/connection.py", line 548, in run
    self.connection._handle_exception(e, sys.exc_info())
  File "/home/fisk/Projects/MCBOT/pyCraft/minecraft/networking/connection.py", line 494, in _handle_exception
    raise_(*exc_info)
  File "/usr/lib/python3.7/site-packages/future/utils/__init__.py", line 415, in raise_
    raise exc.with_traceback(tb)
  File "/home/fisk/Projects/MCBOT/pyCraft/minecraft/networking/connection.py", line 544, in run
    self._run()
  File "/home/fisk/Projects/MCBOT/pyCraft/minecraft/networking/connection.py", line 582, in _run
    self.connection._react(packet)
  File "/home/fisk/Projects/MCBOT/pyCraft/minecraft/networking/connection.py", line 518, in _react
    listener.call_packet(packet)
  File "/home/fisk/Projects/MCBOT/pyCraft/minecraft/networking/packets/packet_listener.py", line 15, in call_packet
    self.callback(packet)
  File "start.py", line 87, in print_incoming
    print('--> %s' % packet, file=sys.stderr)
  File "/home/fisk/Projects/MCBOT/pyCraft/minecraft/networking/packets/packet.py", line 116, in __repr__
    for a in fields if hasattr(self, a))
  File "/home/fisk/Projects/MCBOT/pyCraft/minecraft/networking/packets/packet.py", line 116, in <genexpr>
    for a in fields if hasattr(self, a))
  File "/home/fisk/Projects/MCBOT/pyCraft/minecraft/networking/packets/clientbound/play/player_list_item_packet.py", line 28, in field_string
    return super(PlayerListItemPacket, self).field_string(field)
  File "/home/fisk/Projects/MCBOT/pyCraft/minecraft/networking/packets/packet.py", line 139, in field_string
    return repr(value)
  File "/home/fisk/Projects/MCBOT/pyCraft/minecraft/networking/types/utility.py", line 68, in __repr__
    '%s=%r' % (a, getattr(self, a)) for a in self._all_slots()))
  File "/home/fisk/Projects/MCBOT/pyCraft/minecraft/networking/types/utility.py", line 68, in <genexpr>
    '%s=%r' % (a, getattr(self, a)) for a in self._all_slots()))
AttributeError: 'UpdateLatencyAction' object has no attribute 'p'

**Comment by joodicator** [comment] 2019-07-03 18:02
Thank you for the report. This is now fixed on the `master` branch.

This is a bug caused by the `__slots__` attribute of `PlayerListItemPacket.UpdateLatencyAction` being defined as a string (namely, `'ping'`), but its superclass `MutableRecord` expecting the `__slots__` to be an iterable of slot strings. Hence, `UpdateLatencyAction` was interpreted as having 4 slots called `p`, `i`, `n`, and `g`.

This was fixed by modifying `MutableRecord` so that it properly interprets a `__slots__` of string type as a single slot. The missing test coverage that caused this to go unnoticed until now has also been added.

**Closed by joodicator** 2019-07-03 18:02 UTC
Labels: bug

**Comment by Fisk24** [comment] 2019-07-04 01:45
Wow that was fast thanks!

**Comment by joodicator** [comment] 2019-07-04 20:51
That's what she said.
